version: '2'

services:
  apache2:
    build: ./apache2
    ports:
      - "80:80"
    environment:
      - XDEBUG_CONFIG="remote_host=192.168.22.1"
    volumes:
      - ./apache2/sites:/etc/apache2/sites-available
      - ./apache2/php.ini:/usr/local/etc/php/php.ini
      - ./apache2/info.php:/var/www/html/public/info.php
      - /home/ubuntu/sites:/var/www/html

  mariadb:
    build: ./mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=loho
      - MYSQL_USER=loho
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - /home/ubuntu/data/mariadb:/var/lib/mysql
